### ISSUE TITLE
Error ( Please help)

### ISSUE THREAD

**Issue by amster69** [Th3Hurrican3/mitm#2]
root@kali:~/Desktop/tools/MITM/mitm# python3 mitm.py

	::::    :::: ::::::::::::::::::::::::::    :::: 
	+:+:+: :+:+:+    :+:        :+:    +:+:+: :+:+:+
	+:+ +:+:+ +:+    +:+        +:+    +:+ +:+:+ +:+
	+#+  +:+  +#+    +#+        +#+    +#+  +:+  +#+
	+#+       +#+    +#+        +#+    +#+       +#+
	#+#       #+#    #+#        #+#    #+#       #+#
	###       ##############    ###    ###       ###

		Th3Hurrican3

[*] Available network interfaces:

	0) lo
	1) eth0
	2) tun0
	3) wlan0

mitm:interface> 2

[*] Available hosts:

Traceback (most recent call last):
  File "mitm.py", line 43, in <module>
    discover.discover(net.get_attacker_ip(), net.get_net_mask())
  File "/root/Desktop/tools/MITM/mitm/netdiscover.py", line 22, in discover
    nm = nmap.PortScanner()
AttributeError: module 'nmap' has no attribute 'PortScanner'
root@kali:~/Desktop/tools/MITM/mitm#

**Comment by Gurkinator1** [comment]
I have the same issue, I found that it happens because of a wrong import (python-nmap3 instead of nmap) inside the netdiscover.py

**Comment by Gurkinator1** [comment]
I tried fixing it using https://pypi.org/project/python3-nmap/
